site_name: Recon
site_description: Debug annotated Named Entity Recognition (NER) data for inconsitencies and get insights on improving the quality of your data.
site_url: https://microsoft.github.io/reconner/

theme:
    name: 'material'
    palette:
        primary: 'orange'
        accent: 'deep-orange'
    logo: 'img/drone-white.svg'
    favicon: 'img/favicon.ico'

repo_name: 'microsoft/reconner'
repo_url: 'https://github.com/microsoft/reconner'
edit_uri: 'https://github.com/microsoft/reconner/tree/master/docs'

nav:
    - Recon: 'index.md'
    - Tutorial:
        - Loading your data: 'tutorial/loading_data.md'
        - NER Stats: 'tutorial/ner_stats.md'
        - Using a Corpus: 'tutorial/corpus_apply.md'
        - Getting Insights: 'tutorial/getting_insights.md'
        - Custom EntityRecognizer: 'tutorial/custom_entity_recognizer.md'
    - API Reference:
        - Corpus: 'api/corpus.md'
        - Corrections: 'api/corrections.md'
        - Insights: 'api/insights.md'
        - Loaders: 'api/loaders.md'
        - Stats: 'api/stats.md'
        - Validation: 'api/validation.md'
        - Recognizers:
            - EntityRecognizer: 'api/recognizers/base.md'
            - SpacyEntityRecognizer: 'api/recognizers/spacy.md'
        - Types: 'api/types/example.md'
    - Development - Contributing: 'contributing.md'
    - Release Notes: release-notes.md

markdown_extensions:
    - toc:
        permalink: true
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs
    - admonition
    - codehilite
    - extra

plugins:
  - mkdocstrings

extra:
    social:
        - type: 'github'
          link: 'https://github.com/microsoft/reconner'
        - type: 'twitter'
          link: 'https://twitter.com/kabir_khan14'

extra_css:
    - 'css/termynal.css'
    - 'css/custom.css'

extra_javascript:
    - 'js/termynal.js'
    - 'js/custom.js'
