site_name: Recon
site_description: Debug annotated Named Entity Recognition (NER) data for inconsitencies and get insights on improving the quality of your data.
site_url: https://kabirkhan.github.io/recon/

theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'blue'
    icon:
        repo: 'fontawesome/brands/github-alt'
    logo: 'img/drone-white.svg'
    favicon: 'img/favicon.ico'
    custom_dir: docs/overrides

repo_name: 'kabirkhan/recon'
repo_url: 'https://github.com/kabirkhan/recon'
edit_uri: 'https://github.com/kabirkhan/recon/tree/master/docs'

nav:
    - Recon: 'index.md'
    - Tutorial:
        - Loading your data: 'tutorial/1_loading_data.md'
        - NER Stats: 'tutorial/2_ner_stats.md'
        - Dataset:
            - Introduction: 'tutorial/3_dataset_intro.md'
            - Making changes to a Dataset: 'tutorial/3_dataset_mutate.md'
        - Using a Corpus: 'tutorial/4_corpus.md'
        - More NER Stats: 'tutorial/4_more_stats.md'
        - Getting Insights: 'tutorial/5_getting_insights.md'
        - Custom EntityRecognizer: 'tutorial/custom_entity_recognizer.md'
    - API Reference:
        - Corpus: 'api/corpus.md'
        - Corrections: 'api/corrections.md'
        - Dataset: 'api/dataset.md'
        - Hashing: 'api/hashing.md'
        - Insights: 'api/insights.md'
        - Loaders: 'api/loaders.md'
        - Operations: 'api/operations.md'
        - Stats: 'api/stats.md'
        - Store: 'api/store.md'
        - Tokenization: 'api/tokenization.md'
        - Validation: 'api/validation.md'
        - Recognizers:
            - EntityRecognizer: 'api/recognizers/base.md'
            - SpacyEntityRecognizer: 'api/recognizers/spacy.md'
        - Types: 'api/types/example.md'
    - Release Notes: release-notes.md

markdown_extensions:
    - toc:
        permalink: true
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs
    - admonition
    - codehilite
    - extra
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
  - mkdocstrings

extra:
    social:
        - icon: 'fontawesome/brands/github-alt'
          link: 'https://github.com/kabirkhan/recon'
        - icon: 'fontawesome/brands/twitter'
          link: 'https://twitter.com/kabir_khan14'

extra_css:
    - 'css/termynal.css'
    - 'css/custom.css'

extra_javascript:
    - 'js/termynal.js'
    - 'https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js'
    - 'js/custom.js'
